notifications:
  email:
    on_success: never
    on_failure: change
language: ruby
dist: trusty
bundler_args: --without debug release
rvm:
  - 2.5.3
  - 2.6.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
